initialbalance =int(input("enter the initial balance"))
depositamount =int(input("enter the amount you want to deposit"))
print("intial amount:",initialbalance)
print("amount deposited",depositamount)
print("total amount:",initialbalance+depositamount)